---
- name: Gather facts
  hosts: all
  become: true
  tasks:
  - name: print debug info
    debug: var=inventory_hostname

- name: Install Consul
  hosts: consul_instances
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
  - brianshumate.consul

- name: Install Postgres
  hosts: postgres
  become: true
  tasks:
  - name: print debug info
    debug: var=inventory_hostname
